name: Deploy gRPC Backend to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

env:
  IMAGE_NAME: am-to-mxm_grpc

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: dockertag
        name: Get Docker tag
        uses: ASzc/change-string-case-action@v6
        with:
          string: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./grpc.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.dockertag.outputs.lowercase }}
